version: "3"
services:
    python:
        container_name: standard-backend
        build:
            context: app
            dockerfile: app.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
    python-queue:
        container_name: group-queue
        build:
            context: app
            dockerfile: queue.Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./app:/app