version: "3"
services:
    python:
        container_name: standard-backend
        build:
            context: app
            dockerfile: app.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app