version: "3"
services:
    standard-backend:
        build:
            context: app
            dockerfile: app.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
    group-queue:
        build:
            context: app
            dockerfile: queue.Dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./app:/app